import 'package:flutter/material.dart';
import '../models/drinks.dart';
final List dummy_drinks = [
  DrinksOpt("Green Tea",
      10,
      "img20.jpg", 
      Colors.red,
      "has been hailed for its health benefits in Asian countries for centuries"),
  DrinksOpt("Pomegranate Juice", 
      15, 
      "img21.jpg",
      Colors.red,
      "All-natural pomegranate juice is one of the most nutritious beverages on supermarket shelves"),
  DrinksOpt("Beet Juice",
      10,
      "img22.jpg", 
      Colors.red,
      "are abundant, starting with the fact that they’re a powerful source of folic acid"),
  DrinksOpt("Lemon Water",
      20,
      "img23.jpg",
      Colors.red,
      "Lemon water is a surprisingly powerful immune booster"),
  DrinksOpt("Kombucha",
      20,
      "img24.jpg",
      Colors.red,
      " This elixir is one of the hottest healthy drinks on the market"),
  DrinksOpt("Coconut Water",
      25,
      "img25.jpg",
      Colors.red,
      "The flavor of this tropical water is a bit controversial. Some people love it, and some hate it"),
  DrinksOpt("Hot Chocolate",
      15, 
      "img26.jpg",
      Colors.red, 
      "Who knew treats could be nutritious? We’ve all heard about the health benefits of cacao"),
  DrinksOpt("Cranberry Juice",
      10,
      "img27.jpg",
      Colors.red,
      "This tangy juice is packed with antioxidants that can help prevent cardiovascular "),
  DrinksOpt("Red Wine",
      20, 
      "img28.jpg",
      Colors.red, 
      "Thought red wine was only good for kicking back and relaxing? Think again"),
  DrinksOpt("Orange Juice",
      25,
      "img29.jpg",
      Colors.red,
      "Possibly the most ubiquitous juice on the market, fresh orange juice is one ")
  

];