import 'package:li_food/models/food.dart';
import 'package:flutter/material.dart';
final List dummy_food = [
  FoodOpt("Burgar",
      100,
      "img0.jpg",
      Colors.red ,
      "this is the first food you can got it's and it's the best food for you "),
  FoodOpt("Salad ",
      50,
      "img1.jpg",
      Colors.red,
      "it's a cucumber and tomato and some salt "),
  FoodOpt("Yellow Rice",
      150,
      "img2.jpg",
      Colors.red,
      "this is a yellow rice without chicken and without a lot of salt"),
  FoodOpt("Spagetti",
      150,
      "img3.jpg",
      Colors.red,
      "this is a spagetti with a lot of salt "),
  FoodOpt("pizza",
      200,
      "img4.jpg",
      Colors.red,
      "this is the best option for you the pizza and the name enough"),
  FoodOpt("molokhia",
      150,
      "img5.jpg",
      Colors.red,
      "this is the molokhia plant but it's boiled "),
  FoodOpt("fried fish",
      250,
      "img6.jpg",
      Colors.red,
      "this is a fried fish and without salt "),
  FoodOpt("sfeha",
      200,
      "img7.jpg",
      Colors.red,
      "this is very good option for ypu the sfeha if you want to try it try free"),
  FoodOpt("meet",
      300,
      "img8.jpg",
      Colors.red,
      "this is important thing and you should eat it's to your health"),
  FoodOpt("Khinkhali",
      200,
      "img9.jpg",
      Colors.red,
      "this is very delicious and new option for you try it for free"),
  FoodOpt("musakhan",
      300,
      "img10.jpg",
      Colors.red,
      "this is a very tasty food to eat it in the lunch particular "),
  FoodOpt("Chickens",
      350,
      "img11.jpg",
      Colors.red,
      "it's very important and you should eat it's every week ")

];